apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- vote_staging_deployment.yaml
- vote_services.yaml
replicas:
- name: vote
  count: 7
images:
- name: schoolofdevops/vote:v3
  newName: rotimi98/vote
  newTag: main-2d5ec47e-1662305412 # {"$imagepolicy": "flux-system:vote:tag"}
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "8378185 Inc"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
